name: Build c8-minimal docker image

on:
  push:
    branches: [ develop ]
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
      - 'sl7/**'
      - 'sl7-minimal/*'
      - 'sl7-ci/**'
      - 'c8/**'
      - 'c8-ci/**'
      - '.github/**'

  workflow_dispatch:

jobs:

  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    environment: dockerhub
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            dunedaq/c8-minimal
            ghcr.io/DUNE-DAQ/c8-minimal
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=tag
      
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./c8-minimal
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
